# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    # Task 7: 4-Slot Discovery Cycle Test
    obj = bld.create_ns3_program('task-7-test', ['ble-mesh-discovery'])
    obj.source = 'task-7-test.cc'

    # Task 8: Message Forwarding Queue Test
    obj = bld.create_ns3_program('task-8-test', ['ble-mesh-discovery'])
    obj.source = 'task-8-test.cc'

    # Task 9: Picky Forwarding Algorithm Test
    obj = bld.create_ns3_program('task-9-test', ['ble-mesh-discovery'])
    obj.source = 'task-9-test.cc'

    # Future task tests will be added here
    # obj = bld.create_ns3_program('task-10-test', ['ble-mesh-discovery'])
    # obj.source = 'task-10-test.cc'
